// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type TimekeepingHistory struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Day       int32          `json:"day"`
	Month     int32          `json:"month"`
	Year      int32          `json:"year"`
	IsActive  sql.NullBool   `json:"is_active"`
	Data      sql.NullString `json:"data"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
