// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTimekeepingHistory(ctx context.Context, arg CreateTimekeepingHistoryParams) (sql.Result, error)
	GetTimekeepingHistoryAtMonthByUserId(ctx context.Context, arg GetTimekeepingHistoryAtMonthByUserIdParams) ([]TimekeepingHistory, error)
	GetTimekeepingHistoryByDuration(ctx context.Context, arg GetTimekeepingHistoryByDurationParams) ([]TimekeepingHistory, error)
	GetTimekeepingHistoryInDayByUserId(ctx context.Context, arg GetTimekeepingHistoryInDayByUserIdParams) (TimekeepingHistory, error)
	GetTimekeepingHistoryInYearByUserId(ctx context.Context, arg GetTimekeepingHistoryInYearByUserIdParams) ([]TimekeepingHistory, error)
	UpdateTimekeepingHistoryInDay(ctx context.Context, arg UpdateTimekeepingHistoryInDayParams) (sql.Result, error)
	Close() error
}

var _ Querier = (*Queries)(nil)
