// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: cv_service/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CVServiceClient is the client API for CVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CVServiceClient interface {
	GetCICByUserId(ctx context.Context, in *GetCICByUserIdRequest, opts ...grpc.CallOption) (*GetCICByUserIdResponse, error)
	RegisterUserFace(ctx context.Context, in *RegisterUserFaceRequest, opts ...grpc.CallOption) (*RegisterUserFaceResponse, error)
	AuthorizeUserFace(ctx context.Context, in *AuthorizeUserFaceRequest, opts ...grpc.CallOption) (*AuthorizeUserFaceResponse, error)
	UpsertCICForUser(ctx context.Context, in *UpsertCICForUserRequest, opts ...grpc.CallOption) (*UpsertCICForUserResponse, error)
}

type cVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCVServiceClient(cc grpc.ClientConnInterface) CVServiceClient {
	return &cVServiceClient{cc}
}

func (c *cVServiceClient) GetCICByUserId(ctx context.Context, in *GetCICByUserIdRequest, opts ...grpc.CallOption) (*GetCICByUserIdResponse, error) {
	out := new(GetCICByUserIdResponse)
	err := c.cc.Invoke(ctx, "/cv_service.api.CVService/GetCICByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cVServiceClient) RegisterUserFace(ctx context.Context, in *RegisterUserFaceRequest, opts ...grpc.CallOption) (*RegisterUserFaceResponse, error) {
	out := new(RegisterUserFaceResponse)
	err := c.cc.Invoke(ctx, "/cv_service.api.CVService/RegisterUserFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cVServiceClient) AuthorizeUserFace(ctx context.Context, in *AuthorizeUserFaceRequest, opts ...grpc.CallOption) (*AuthorizeUserFaceResponse, error) {
	out := new(AuthorizeUserFaceResponse)
	err := c.cc.Invoke(ctx, "/cv_service.api.CVService/AuthorizeUserFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cVServiceClient) UpsertCICForUser(ctx context.Context, in *UpsertCICForUserRequest, opts ...grpc.CallOption) (*UpsertCICForUserResponse, error) {
	out := new(UpsertCICForUserResponse)
	err := c.cc.Invoke(ctx, "/cv_service.api.CVService/UpsertCICForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CVServiceServer is the server API for CVService service.
// All implementations must embed UnimplementedCVServiceServer
// for forward compatibility
type CVServiceServer interface {
	GetCICByUserId(context.Context, *GetCICByUserIdRequest) (*GetCICByUserIdResponse, error)
	RegisterUserFace(context.Context, *RegisterUserFaceRequest) (*RegisterUserFaceResponse, error)
	AuthorizeUserFace(context.Context, *AuthorizeUserFaceRequest) (*AuthorizeUserFaceResponse, error)
	UpsertCICForUser(context.Context, *UpsertCICForUserRequest) (*UpsertCICForUserResponse, error)
	mustEmbedUnimplementedCVServiceServer()
}

// UnimplementedCVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCVServiceServer struct {
}

func (UnimplementedCVServiceServer) GetCICByUserId(context.Context, *GetCICByUserIdRequest) (*GetCICByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCICByUserId not implemented")
}
func (UnimplementedCVServiceServer) RegisterUserFace(context.Context, *RegisterUserFaceRequest) (*RegisterUserFaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserFace not implemented")
}
func (UnimplementedCVServiceServer) AuthorizeUserFace(context.Context, *AuthorizeUserFaceRequest) (*AuthorizeUserFaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeUserFace not implemented")
}
func (UnimplementedCVServiceServer) UpsertCICForUser(context.Context, *UpsertCICForUserRequest) (*UpsertCICForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCICForUser not implemented")
}
func (UnimplementedCVServiceServer) mustEmbedUnimplementedCVServiceServer() {}

// UnsafeCVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CVServiceServer will
// result in compilation errors.
type UnsafeCVServiceServer interface {
	mustEmbedUnimplementedCVServiceServer()
}

func RegisterCVServiceServer(s grpc.ServiceRegistrar, srv CVServiceServer) {
	s.RegisterService(&CVService_ServiceDesc, srv)
}

func _CVService_GetCICByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCICByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).GetCICByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cv_service.api.CVService/GetCICByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).GetCICByUserId(ctx, req.(*GetCICByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CVService_RegisterUserFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).RegisterUserFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cv_service.api.CVService/RegisterUserFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).RegisterUserFace(ctx, req.(*RegisterUserFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CVService_AuthorizeUserFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeUserFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).AuthorizeUserFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cv_service.api.CVService/AuthorizeUserFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).AuthorizeUserFace(ctx, req.(*AuthorizeUserFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CVService_UpsertCICForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCICForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).UpsertCICForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cv_service.api.CVService/UpsertCICForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).UpsertCICForUser(ctx, req.(*UpsertCICForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CVService_ServiceDesc is the grpc.ServiceDesc for CVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cv_service.api.CVService",
	HandlerType: (*CVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCICByUserId",
			Handler:    _CVService_GetCICByUserId_Handler,
		},
		{
			MethodName: "RegisterUserFace",
			Handler:    _CVService_RegisterUserFace_Handler,
		},
		{
			MethodName: "AuthorizeUserFace",
			Handler:    _CVService_AuthorizeUserFace_Handler,
		},
		{
			MethodName: "UpsertCICForUser",
			Handler:    _CVService_UpsertCICForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cv_service/api/api.proto",
}
