// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: gateway/api/data.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNewUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password            string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CitizenIdentityCard *CitizenIdentityCard `protobuf:"bytes,2,opt,name=citizen_identity_card,json=citizenIdentityCard,proto3" json:"citizen_identity_card,omitempty"`
}

func (x *RegisterNewUserRequest) Reset() {
	*x = RegisterNewUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserRequest) ProtoMessage() {}

func (x *RegisterNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterNewUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNewUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterNewUserRequest) GetCitizenIdentityCard() *CitizenIdentityCard {
	if x != nil {
		return x.CitizenIdentityCard
	}
	return nil
}

type CitizenIdentityCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegisterDate string `protobuf:"bytes,2,opt,name=register_date,json=registerDate,proto3" json:"register_date,omitempty"`
	ExpireDate   string `protobuf:"bytes,3,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Provider     string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Born         string `protobuf:"bytes,5,opt,name=born,proto3" json:"born,omitempty"`
}

func (x *CitizenIdentityCard) Reset() {
	*x = CitizenIdentityCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenIdentityCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenIdentityCard) ProtoMessage() {}

func (x *CitizenIdentityCard) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenIdentityCard.ProtoReflect.Descriptor instead.
func (*CitizenIdentityCard) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{1}
}

func (x *CitizenIdentityCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CitizenIdentityCard) GetRegisterDate() string {
	if x != nil {
		return x.RegisterDate
	}
	return ""
}

func (x *CitizenIdentityCard) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *CitizenIdentityCard) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CitizenIdentityCard) GetBorn() string {
	if x != nil {
		return x.Born
	}
	return ""
}

type RegisterNewUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegisterNewUserResponse) Reset() {
	*x = RegisterNewUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserResponse) ProtoMessage() {}

func (x *RegisterNewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterNewUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNewUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterNewUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gateway_api_data_proto protoreflect.FileDescriptor

var file_gateway_api_data_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x9e, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x54, 0x0a, 0x15, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69,
	0x74, 0x69, 0x7a, 0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x13, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x43, 0x69, 0x74, 0x69, 0x7a,
	0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x72, 0x6e, 0x22, 0x47, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_api_data_proto_rawDescOnce sync.Once
	file_gateway_api_data_proto_rawDescData = file_gateway_api_data_proto_rawDesc
)

func file_gateway_api_data_proto_rawDescGZIP() []byte {
	file_gateway_api_data_proto_rawDescOnce.Do(func() {
		file_gateway_api_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_api_data_proto_rawDescData)
	})
	return file_gateway_api_data_proto_rawDescData
}

var file_gateway_api_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_api_data_proto_goTypes = []interface{}{
	(*RegisterNewUserRequest)(nil),  // 0: gateway.api.RegisterNewUserRequest
	(*CitizenIdentityCard)(nil),     // 1: gateway.api.CitizenIdentityCard
	(*RegisterNewUserResponse)(nil), // 2: gateway.api.RegisterNewUserResponse
}
var file_gateway_api_data_proto_depIdxs = []int32{
	1, // 0: gateway.api.RegisterNewUserRequest.citizen_identity_card:type_name -> gateway.api.CitizenIdentityCard
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_api_data_proto_init() }
func file_gateway_api_data_proto_init() {
	if File_gateway_api_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_api_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenIdentityCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_api_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_api_data_proto_goTypes,
		DependencyIndexes: file_gateway_api_data_proto_depIdxs,
		MessageInfos:      file_gateway_api_data_proto_msgTypes,
	}.Build()
	File_gateway_api_data_proto = out.File
	file_gateway_api_data_proto_rawDesc = nil
	file_gateway_api_data_proto_goTypes = nil
	file_gateway_api_data_proto_depIdxs = nil
}
