// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: gateway/api/data.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_OTHER   UserRole = 0
	UserRole_STAFF   UserRole = 1
	UserRole_MANAGER UserRole = 2
	UserRole_HR      UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "OTHER",
		1: "STAFF",
		2: "MANAGER",
		3: "HR",
	}
	UserRole_value = map[string]int32{
		"OTHER":   0,
		"STAFF":   1,
		"MANAGER": 2,
		"HR":      3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_api_data_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_gateway_api_data_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{0}
}

type RegisterNewUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId string   `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password   string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email      string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role       UserRole `protobuf:"varint,5,opt,name=role,proto3,enum=gateway.api.UserRole" json:"role,omitempty"`
	Position   string   `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Department string   `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	Gender     string   `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Address    string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Phone      string   `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *RegisterNewUserRequest) Reset() {
	*x = RegisterNewUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserRequest) ProtoMessage() {}

func (x *RegisterNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterNewUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNewUserRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *RegisterNewUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterNewUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterNewUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_OTHER
}

func (x *RegisterNewUserRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *RegisterNewUserRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *RegisterNewUserRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterNewUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNewUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateCitizenIdentityCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCitizenIdentityCardRequest) Reset() {
	*x = UpdateCitizenIdentityCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCitizenIdentityCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCitizenIdentityCardRequest) ProtoMessage() {}

func (x *UpdateCitizenIdentityCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCitizenIdentityCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCitizenIdentityCardRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{1}
}

type UpdateCitizenIdentityCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *CitizenIdentityCard `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCitizenIdentityCardResponse) Reset() {
	*x = UpdateCitizenIdentityCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCitizenIdentityCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCitizenIdentityCardResponse) ProtoMessage() {}

func (x *UpdateCitizenIdentityCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCitizenIdentityCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCitizenIdentityCardResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCitizenIdentityCardResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCitizenIdentityCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCitizenIdentityCardResponse) GetData() *CitizenIdentityCard {
	if x != nil {
		return x.Data
	}
	return nil
}

type CitizenIdentityCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegisterDate int64  `protobuf:"varint,2,opt,name=register_date,json=registerDate,proto3" json:"register_date,omitempty"`
	ExpireDate   int64  `protobuf:"varint,3,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Provider     string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Born         int64  `protobuf:"varint,5,opt,name=born,proto3" json:"born,omitempty"`
}

func (x *CitizenIdentityCard) Reset() {
	*x = CitizenIdentityCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenIdentityCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenIdentityCard) ProtoMessage() {}

func (x *CitizenIdentityCard) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenIdentityCard.ProtoReflect.Descriptor instead.
func (*CitizenIdentityCard) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{3}
}

func (x *CitizenIdentityCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CitizenIdentityCard) GetRegisterDate() int64 {
	if x != nil {
		return x.RegisterDate
	}
	return 0
}

func (x *CitizenIdentityCard) GetExpireDate() int64 {
	if x != nil {
		return x.ExpireDate
	}
	return 0
}

func (x *CitizenIdentityCard) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CitizenIdentityCard) GetBorn() int64 {
	if x != nil {
		return x.Born
	}
	return 0
}

type RegisterNewUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterNewUserResponse) Reset() {
	*x = RegisterNewUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserResponse) ProtoMessage() {}

func (x *RegisterNewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterNewUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterNewUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterNewUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNewUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthorizeUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email      string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmployeeId string `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthorizeUserRequest) Reset() {
	*x = AuthorizeUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeUserRequest) ProtoMessage() {}

func (x *AuthorizeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeUserRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizeUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorizeUserRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *AuthorizeUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorizeUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthorizeUserResponse) Reset() {
	*x = AuthorizeUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeUserResponse) ProtoMessage() {}

func (x *AuthorizeUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeUserResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizeUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthorizeUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthorizeUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterCICForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Front  []byte `protobuf:"bytes,2,opt,name=front,proto3" json:"front,omitempty"`
	Back   []byte `protobuf:"bytes,3,opt,name=back,proto3" json:"back,omitempty"`
}

func (x *RegisterCICForUserRequest) Reset() {
	*x = RegisterCICForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCICForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCICForUserRequest) ProtoMessage() {}

func (x *RegisterCICForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCICForUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterCICForUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterCICForUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterCICForUserRequest) GetFront() []byte {
	if x != nil {
		return x.Front
	}
	return nil
}

func (x *RegisterCICForUserRequest) GetBack() []byte {
	if x != nil {
		return x.Back
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{8}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterCICForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *CitizenIdentityCard `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RegisterCICForUserResponse) Reset() {
	*x = RegisterCICForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_api_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCICForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCICForUserResponse) ProtoMessage() {}

func (x *RegisterCICForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCICForUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterCICForUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_data_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterCICForUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterCICForUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterCICForUserResponse) GetData() *CitizenIdentityCard {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gateway_api_data_proto protoreflect.FileDescriptor

var file_gateway_api_data_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x2a, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x65,
	0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd1, 0x02, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65,
	0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0b,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x32, 0x52, 0x0a, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18,
	0xff, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72,
	0x05, 0x10, 0x08, 0x18, 0xff, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x21, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65,
	0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xb6, 0x01, 0x0a, 0x13, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x0d, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x04, 0x62, 0x6f, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x72, 0x6e, 0x22, 0x5d, 0x0a, 0x17,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x14,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2a, 0x0a, 0x0b, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x0a, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10,
	0x08, 0x18, 0xff, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5b,
	0x0a, 0x15, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x67, 0x0a, 0x19, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x49, 0x43, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02,
	0x20, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x61, 0x63, 0x6b, 0x22, 0x1b, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x80, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x49,
	0x43, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x69, 0x7a,
	0x65, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0x35, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x54, 0x41, 0x46, 0x46, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x52, 0x10, 0x03, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_api_data_proto_rawDescOnce sync.Once
	file_gateway_api_data_proto_rawDescData = file_gateway_api_data_proto_rawDesc
)

func file_gateway_api_data_proto_rawDescGZIP() []byte {
	file_gateway_api_data_proto_rawDescOnce.Do(func() {
		file_gateway_api_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_api_data_proto_rawDescData)
	})
	return file_gateway_api_data_proto_rawDescData
}

var file_gateway_api_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_api_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gateway_api_data_proto_goTypes = []interface{}{
	(UserRole)(0),                             // 0: gateway.api.UserRole
	(*RegisterNewUserRequest)(nil),            // 1: gateway.api.RegisterNewUserRequest
	(*UpdateCitizenIdentityCardRequest)(nil),  // 2: gateway.api.UpdateCitizenIdentityCardRequest
	(*UpdateCitizenIdentityCardResponse)(nil), // 3: gateway.api.UpdateCitizenIdentityCardResponse
	(*CitizenIdentityCard)(nil),               // 4: gateway.api.CitizenIdentityCard
	(*RegisterNewUserResponse)(nil),           // 5: gateway.api.RegisterNewUserResponse
	(*AuthorizeUserRequest)(nil),              // 6: gateway.api.AuthorizeUserRequest
	(*AuthorizeUserResponse)(nil),             // 7: gateway.api.AuthorizeUserResponse
	(*RegisterCICForUserRequest)(nil),         // 8: gateway.api.RegisterCICForUserRequest
	(*Image)(nil),                             // 9: gateway.api.Image
	(*RegisterCICForUserResponse)(nil),        // 10: gateway.api.RegisterCICForUserResponse
}
var file_gateway_api_data_proto_depIdxs = []int32{
	0, // 0: gateway.api.RegisterNewUserRequest.role:type_name -> gateway.api.UserRole
	4, // 1: gateway.api.UpdateCitizenIdentityCardResponse.data:type_name -> gateway.api.CitizenIdentityCard
	4, // 2: gateway.api.RegisterCICForUserResponse.data:type_name -> gateway.api.CitizenIdentityCard
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_api_data_proto_init() }
func file_gateway_api_data_proto_init() {
	if File_gateway_api_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_api_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCitizenIdentityCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCitizenIdentityCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenIdentityCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCICForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_api_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCICForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_api_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_api_data_proto_goTypes,
		DependencyIndexes: file_gateway_api_data_proto_depIdxs,
		EnumInfos:         file_gateway_api_data_proto_enumTypes,
		MessageInfos:      file_gateway_api_data_proto_msgTypes,
	}.Build()
	File_gateway_api_data_proto = out.File
	file_gateway_api_data_proto_rawDesc = nil
	file_gateway_api_data_proto_goTypes = nil
	file_gateway_api_data_proto_depIdxs = nil
}
