// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserInfoStmt, err = db.PrepareContext(ctx, createUserInfo); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserInfo: %w", err)
	}
	if q.getUserInfoByTokenStmt, err = db.PrepareContext(ctx, getUserInfoByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInfoByToken: %w", err)
	}
	if q.getUserInfoByUsernameOrEmailStmt, err = db.PrepareContext(ctx, getUserInfoByUsernameOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInfoByUsernameOrEmail: %w", err)
	}
	if q.updateUserCardStmt, err = db.PrepareContext(ctx, updateUserCard); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserCard: %w", err)
	}
	if q.updateUserInfoTokenByUserIdStmt, err = db.PrepareContext(ctx, updateUserInfoTokenByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserInfoTokenByUserId: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserInfoStmt != nil {
		if cerr := q.createUserInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserInfoStmt: %w", cerr)
		}
	}
	if q.getUserInfoByTokenStmt != nil {
		if cerr := q.getUserInfoByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInfoByTokenStmt: %w", cerr)
		}
	}
	if q.getUserInfoByUsernameOrEmailStmt != nil {
		if cerr := q.getUserInfoByUsernameOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInfoByUsernameOrEmailStmt: %w", cerr)
		}
	}
	if q.updateUserCardStmt != nil {
		if cerr := q.updateUserCardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserCardStmt: %w", cerr)
		}
	}
	if q.updateUserInfoTokenByUserIdStmt != nil {
		if cerr := q.updateUserInfoTokenByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserInfoTokenByUserIdStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createUserInfoStmt               *sql.Stmt
	getUserInfoByTokenStmt           *sql.Stmt
	getUserInfoByUsernameOrEmailStmt *sql.Stmt
	updateUserCardStmt               *sql.Stmt
	updateUserInfoTokenByUserIdStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createUserInfoStmt:               q.createUserInfoStmt,
		getUserInfoByTokenStmt:           q.getUserInfoByTokenStmt,
		getUserInfoByUsernameOrEmailStmt: q.getUserInfoByUsernameOrEmailStmt,
		updateUserCardStmt:               q.updateUserCardStmt,
		updateUserInfoTokenByUserIdStmt:  q.updateUserInfoTokenByUserIdStmt,
	}
}
