// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type UserInfo struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	ExtraData sql.NullString `json:"extra_data"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
