// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateNewUserInfo(ctx context.Context, arg CreateNewUserInfoParams) (sql.Result, error)
	GetUserInfoById(ctx context.Context, id int64) (UserInfo, error)
	UpdateUserInfoByUsername(ctx context.Context, arg UpdateUserInfoByUsernameParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
