// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (sql.Result, error)
	GetUserInfoByToken(ctx context.Context, token string) (UserInfo, error)
	GetUserInfoByUsernameOrEmail(ctx context.Context, arg GetUserInfoByUsernameOrEmailParams) (UserInfo, error)
	UpdateUserCard(ctx context.Context, arg UpdateUserCardParams) (sql.Result, error)
	UpdateUserInfoTokenByUserId(ctx context.Context, arg UpdateUserInfoTokenByUserIdParams) (sql.Result, error)
	Close() error
}

var _ Querier = (*Queries)(nil)
