// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type CitizenIdentifyCard struct {
	UserID    int64          `json:"user_id"`
	Data      sql.NullString `json:"data"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type UserFace struct {
	UserID    int64          `json:"user_id"`
	Data      sql.NullString `json:"data"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
