// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCICByUserId(ctx context.Context, arg CreateCICByUserIdParams) (sql.Result, error)
	CreateFaceByUserId(ctx context.Context, arg CreateFaceByUserIdParams) (sql.Result, error)
	GetCICByUserId(ctx context.Context, userID int64) (CitizenIdentifyCard, error)
	GetCICByUserIdForUpdate(ctx context.Context, userID int64) (CitizenIdentifyCard, error)
	GetFaceByUserId(ctx context.Context, userID int64) (UserFace, error)
	GetFaceByUserIdForUpdate(ctx context.Context, userID int64) (UserFace, error)
	UpdateCICByUserId(ctx context.Context, arg UpdateCICByUserIdParams) (sql.Result, error)
	UpdateFaceByUserId(ctx context.Context, arg UpdateFaceByUserIdParams) (sql.Result, error)
	Close() error
}

var _ Querier = (*Queries)(nil)
