// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: timekeeping_service/api/data.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHistoryOfUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of user
	UserId int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time   *HistoryTime `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GetHistoryOfUserRequest) Reset() {
	*x = GetHistoryOfUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryOfUserRequest) ProtoMessage() {}

func (x *GetHistoryOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryOfUserRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryOfUserRequest) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryOfUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHistoryOfUserRequest) GetTime() *HistoryTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type GetHistoryOfUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*TimekeepingHistory `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetHistoryOfUserResponse) Reset() {
	*x = GetHistoryOfUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryOfUserResponse) ProtoMessage() {}

func (x *GetHistoryOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryOfUserResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryOfUserResponse) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryOfUserResponse) GetData() []*TimekeepingHistory {
	if x != nil {
		return x.Data
	}
	return nil
}

type HistoryTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   uint32 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month uint32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  uint32 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *HistoryTime) Reset() {
	*x = HistoryTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryTime) ProtoMessage() {}

func (x *HistoryTime) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryTime.ProtoReflect.Descriptor instead.
func (*HistoryTime) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryTime) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *HistoryTime) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *HistoryTime) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type TimekeepingHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Day    uint32 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Month  uint32 `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Year   uint32 `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Data   *Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TimekeepingHistory) Reset() {
	*x = TimekeepingHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimekeepingHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimekeepingHistory) ProtoMessage() {}

func (x *TimekeepingHistory) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimekeepingHistory.ProtoReflect.Descriptor instead.
func (*TimekeepingHistory) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{3}
}

func (x *TimekeepingHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TimekeepingHistory) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *TimekeepingHistory) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TimekeepingHistory) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TimekeepingHistory) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalTime uint64       `protobuf:"varint,1,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	StartTime int64        `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64        `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Details   []*Data_Line `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetTotalTime() uint64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *Data) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Data) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Data) GetDetails() []*Data_Line {
	if x != nil {
		return x.Details
	}
	return nil
}

type CreateHistoryOfUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time      *HistoryTime `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	StartTime int64        `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64        `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *CreateHistoryOfUserRequest) Reset() {
	*x = CreateHistoryOfUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHistoryOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryOfUserRequest) ProtoMessage() {}

func (x *CreateHistoryOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryOfUserRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryOfUserRequest) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{5}
}

func (x *CreateHistoryOfUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateHistoryOfUserRequest) GetTime() *HistoryTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateHistoryOfUserRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateHistoryOfUserRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CreateHistoryOfUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateHistoryOfUserResponse) Reset() {
	*x = CreateHistoryOfUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHistoryOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryOfUserResponse) ProtoMessage() {}

func (x *CreateHistoryOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryOfUserResponse.ProtoReflect.Descriptor instead.
func (*CreateHistoryOfUserResponse) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHistoryOfUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateHistoryOfUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Data_Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	StartTime int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *Data_Line) Reset() {
	*x = Data_Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timekeeping_service_api_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Line) ProtoMessage() {}

func (x *Data_Line) ProtoReflect() protoreflect.Message {
	mi := &file_timekeeping_service_api_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Line.ProtoReflect.Descriptor instead.
func (*Data_Line) Descriptor() ([]byte, []int) {
	return file_timekeeping_service_api_data_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Data_Line) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Data_Line) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Data_Line) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_timekeeping_service_api_data_proto protoreflect.FileDescriptor

var file_timekeeping_service_api_data_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x74, 0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x2a, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x22, 0x5b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4f, 0x66,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a,
	0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04,
	0x10, 0x20, 0x28, 0x00, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x10,
	0x0d, 0x28, 0x00, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20,
	0x00, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x54, 0x69, 0x6d, 0x65,
	0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x10, 0x20, 0x20, 0x00, 0x52,
	0x03, 0x64, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x10, 0x0d, 0x20, 0x00, 0x52, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf5, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6b,
	0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x56, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc4, 0x01,
	0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_timekeeping_service_api_data_proto_rawDescOnce sync.Once
	file_timekeeping_service_api_data_proto_rawDescData = file_timekeeping_service_api_data_proto_rawDesc
)

func file_timekeeping_service_api_data_proto_rawDescGZIP() []byte {
	file_timekeeping_service_api_data_proto_rawDescOnce.Do(func() {
		file_timekeeping_service_api_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_timekeeping_service_api_data_proto_rawDescData)
	})
	return file_timekeeping_service_api_data_proto_rawDescData
}

var file_timekeeping_service_api_data_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_timekeeping_service_api_data_proto_goTypes = []interface{}{
	(*GetHistoryOfUserRequest)(nil),     // 0: timekeeping_service.api.GetHistoryOfUserRequest
	(*GetHistoryOfUserResponse)(nil),    // 1: timekeeping_service.api.GetHistoryOfUserResponse
	(*HistoryTime)(nil),                 // 2: timekeeping_service.api.HistoryTime
	(*TimekeepingHistory)(nil),          // 3: timekeeping_service.api.TimekeepingHistory
	(*Data)(nil),                        // 4: timekeeping_service.api.Data
	(*CreateHistoryOfUserRequest)(nil),  // 5: timekeeping_service.api.CreateHistoryOfUserRequest
	(*CreateHistoryOfUserResponse)(nil), // 6: timekeeping_service.api.CreateHistoryOfUserResponse
	(*Data_Line)(nil),                   // 7: timekeeping_service.api.Data.Line
}
var file_timekeeping_service_api_data_proto_depIdxs = []int32{
	2, // 0: timekeeping_service.api.GetHistoryOfUserRequest.time:type_name -> timekeeping_service.api.HistoryTime
	3, // 1: timekeeping_service.api.GetHistoryOfUserResponse.data:type_name -> timekeeping_service.api.TimekeepingHistory
	4, // 2: timekeeping_service.api.TimekeepingHistory.data:type_name -> timekeeping_service.api.Data
	7, // 3: timekeeping_service.api.Data.details:type_name -> timekeeping_service.api.Data.Line
	2, // 4: timekeeping_service.api.CreateHistoryOfUserRequest.time:type_name -> timekeeping_service.api.HistoryTime
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_timekeeping_service_api_data_proto_init() }
func file_timekeeping_service_api_data_proto_init() {
	if File_timekeeping_service_api_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timekeeping_service_api_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryOfUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryOfUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimekeepingHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHistoryOfUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHistoryOfUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timekeeping_service_api_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timekeeping_service_api_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timekeeping_service_api_data_proto_goTypes,
		DependencyIndexes: file_timekeeping_service_api_data_proto_depIdxs,
		MessageInfos:      file_timekeeping_service_api_data_proto_msgTypes,
	}.Build()
	File_timekeeping_service_api_data_proto = out.File
	file_timekeeping_service_api_data_proto_rawDesc = nil
	file_timekeeping_service_api_data_proto_goTypes = nil
	file_timekeeping_service_api_data_proto_depIdxs = nil
}
